name: SYSURS FrondEnd CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm install
    - name: Run lints
      run: npm run lint
    - name: Run unit tests
      run: npm run test:unit
    - name: Run e2e tests
      run: npm run test:e2e